.TH BCALC 1 "2025-11-12" "bcalc 1.0.0" "User Commands"
.SH NAME
bcalc \- Basic Calculator
.SH SYNOPSIS
.B bcalc
.RI [ expression]
.SH DESCRIPTION
Basic Calculator

Directions: enter an equation such as below and press enter
.RS
(1 + 1 * (s(1000/10)))^2 - (121%10) will equal 120.00
.RE

Supports: addition(+), subtraction(-), multiplication(*), division(/), modulus(%), power(^), parentheses(), sqrt(s), previous answer(ans)

.SH OPTIONS
.TP
.B -v --version
Display version
.TP
.B --help
Display help menu

.SH NOTES
To invoke the program when installed, run bcalc:
.IP
bcalc
.SH AUTHOR
Created by Ben Sadel